version: '3'
services:
  inspectra-ui:
    container_name: inspectra-ui
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4012:3000"
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
